(()=>{
const N=12,ABC='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const PHASES=[
 {title:'Estruturas fundamentais',intro:'Encontre componentes essenciais do sistema nervoso central.',medal:'🧭',reward:'Medalha Explorador',words:[
  ['CEREBRO','Centro de integração relacionado a pensamento, percepção e ações voluntárias.'],['CEREBELO','Participa do equilíbrio, postura e coordenação dos movimentos.'],['TRONCO','O tronco encefálico conecta regiões e participa do controle de funções vitais.'],['MEDULA','A medula espinal conduz impulsos e integra muitos reflexos.'],['NEURONIO','Célula especializada em receber e transmitir informações.']]},
 {title:'Lobos e regiões cerebrais',intro:'Explore territórios do córtex e suas funções predominantes.',medal:'🔗',reward:'Medalha Conector',words:[
  ['FRONTAL','Relaciona-se a planejamento, tomada de decisão, linguagem e movimento voluntário.'],['PARIETAL','Integra sensações corporais e contribui para orientação espacial.'],['TEMPORAL','Participa da audição, memória e processamento da linguagem.'],['OCCIPITAL','Região especialmente relacionada ao processamento visual.'],['CORTEX','Camada externa do cérebro, organizada em áreas especializadas.']]},
 {title:'Circuitos e funções',intro:'Descubra palavras que explicam como o sistema nervoso atua.',medal:'🏆',reward:'Troféu Neuro Mestre',words:[
  ['MEMORIA','Capacidade de registrar, armazenar e recuperar informações.'],['EQUILIBRIO','Depende da integração entre cerebelo, sistema vestibular, visão e propriocepção.'],['REFLEXO','Resposta rápida que pode ser integrada na medula espinal.'],['SINAPSE','Região de comunicação funcional entre neurônios ou outras células.'],['LINGUAGEM','Função complexa que envolve redes distribuídas no cérebro.']]}
];
let phase=0,grid=[],placements=[],found=new Set(),selecting=false,startCell=null,currentPath=[],coins=0,score=0,hints=2,font=18,soundOn=true,audios={};
const $=id=>document.getElementById(id);const dirs=[[0,1],[1,0],[1,1],[1,-1],[0,-1],[-1,0],[-1,-1],[-1,1]];
function loadAudio(name){const a=new Audio(`assets/audio/${name}.mp3`);a.preload='auto';audios[name]=a}['clique','erro','vitoria'].forEach(loadAudio);
function play(name){if(!soundOn)return;const a=audios[name];if(!a)return;a.currentTime=0;a.volume=.75;a.play().catch(()=>{})}
function seeded(seed){let x=seed+1;return()=>{x=Math.sin(x*999)*43758.5453;return x-Math.floor(x)}}
function buildPuzzle(){const rnd=seeded(phase*101+37);grid=Array.from({length:N},()=>Array(N).fill(''));placements=[];for(const [word] of PHASES[phase].words){let placed=false;for(let attempt=0;attempt<700&&!placed;attempt++){const [dr,dc]=dirs[Math.floor(rnd()*dirs.length)],r=Math.floor(rnd()*N),c=Math.floor(rnd()*N),er=r+dr*(word.length-1),ec=c+dc*(word.length-1);if(er<0||er>=N||ec<0||ec>=N)continue;let ok=true;for(let i=0;i<word.length;i++){const ch=grid[r+dr*i][c+dc*i];if(ch&&ch!==word[i]){ok=false;break}}if(!ok)continue;const cells=[];for(let i=0;i<word.length;i++){grid[r+dr*i][c+dc*i]=word[i];cells.push((r+dr*i)*N+c+dc*i)}placements.push({word,cells});placed=true}if(!placed)throw new Error('Não foi possível posicionar '+word)}for(let r=0;r<N;r++)for(let c=0;c<N;c++)if(!grid[r][c])grid[r][c]=ABC[Math.floor(rnd()*ABC.length)]}
function render(){const el=$('grid');el.innerHTML='';for(let r=0;r<N;r++)for(let c=0;c<N;c++){const i=r*N+c,b=document.createElement('button');b.className='letter';b.textContent=grid[r][c];b.dataset.index=i;b.setAttribute('role','gridcell');b.setAttribute('aria-label',`Linha ${r+1}, coluna ${c+1}, letra ${grid[r][c]}`);b.addEventListener('pointerdown',e=>begin(i,e));b.addEventListener('pointerenter',()=>extend(i));b.addEventListener('pointerup',finish);el.appendChild(b)}renderWords();updateFoundCells()}
function renderWords(){const el=$('wordList');el.innerHTML='';PHASES[phase].words.forEach(([w])=>{const d=document.createElement('div');d.className='word-item'+(found.has(w)?' found':'');d.id='word-'+w;d.innerHTML=`<span>${w}</span><span>${found.has(w)?'✓':'○'}</span>`;el.appendChild(d)})}
function straightPath(a,b){const ar=Math.floor(a/N),ac=a%N,br=Math.floor(b/N),bc=b%N,dr=Math.sign(br-ar),dc=Math.sign(bc-ac),rd=Math.abs(br-ar),cd=Math.abs(bc-ac);if(!(rd===0||cd===0||rd===cd))return[];const len=Math.max(rd,cd)+1,out=[];for(let i=0;i<len;i++)out.push((ar+dr*i)*N+ac+dc*i);return out}
function begin(i,e){e.preventDefault();selecting=true;startCell=i;currentPath=[i];play('clique');paintPath()}
function extend(i){if(!selecting)return;const path=straightPath(startCell,i);if(path.length){currentPath=path;paintPath()}}
function finish(){if(!selecting)return;selecting=false;const letters=currentPath.map(i=>grid[Math.floor(i/N)][i%N]).join(''),reverse=[...letters].reverse().join(''),match=PHASES[phase].words.find(([w])=>(w===letters||w===reverse)&&!found.has(w));if(match){found.add(match[0]);score+=100;coins+=25;play('vitoria');coinRain();addFact(match[0],match[1]);$('message').textContent=`Você encontrou ${match[0]}! +25 moedas.`;renderWords();updateFoundCells();updateHud();if(found.size===PHASES[phase].words.length)setTimeout(completePhase,900)}else{play('erro');$('message').textContent='Essa sequência não corresponde a uma palavra da fase. Tente novamente.';clearSelecting()}currentPath=[]}
function paintPath(){document.querySelectorAll('.letter').forEach(x=>x.classList.remove('selecting'));currentPath.forEach(i=>document.querySelector(`.letter[data-index="${i}"]`)?.classList.add('selecting'))}
function clearSelecting(){document.querySelectorAll('.letter.selecting').forEach(x=>x.classList.remove('selecting'))}
function updateFoundCells(){clearSelecting();for(const p of placements)if(found.has(p.word))p.cells.forEach(i=>document.querySelector(`.letter[data-index="${i}"]`)?.classList.add('found'))}
function addFact(word,text){$('factCards').querySelector('.empty')?.remove();if($('fact-'+word))return;const a=document.createElement('article');a.className='fact-card';a.id='fact-'+word;a.innerHTML=`<h3>${word}</h3><p>${text}</p>`;$('factCards').appendChild(a)}
function coinRain(){const box=$('coinRain');for(let i=0;i<32;i++){const c=document.createElement('span');c.className='coin';c.textContent='🪙';c.style.left=Math.random()*96+'vw';c.style.setProperty('--dur',(1.1+Math.random()*1.5)+'s');c.style.animationDelay=Math.random()*.4+'s';box.appendChild(c);setTimeout(()=>c.remove(),3200)}}
function hint(){if(hints<=0){$('message').textContent='As duas dicas desta fase já foram usadas.';play('erro');return}const p=placements.find(x=>!found.has(x.word));if(!p)return;hints--;$('hintStatus').textContent=`Dicas disponíveis: ${hints}`;p.cells.slice(0,2).forEach(i=>{const b=document.querySelector(`.letter[data-index="${i}"]`);b.classList.add('hinting');setTimeout(()=>b.classList.remove('hinting'),2400)});$('message').textContent=`Dica: procure ${p.word}. As duas primeiras letras estão piscando.`;play('clique')}
function updateHud(){const p=PHASES[phase];$('phaseHud').textContent=`Fase ${phase+1}/3`;$('coinHud').textContent=`🪙 ${coins}`;$('scoreHud').textContent=`⭐ ${score}`;$('phaseTag').textContent=`MISSÃO ${phase+1}`;$('phaseTitle').textContent=p.title;$('phaseIntro').textContent=p.intro;$('phaseMedal').textContent=p.medal;$('progressFill').style.width=(found.size/p.words.length*100)+'%'}
function initPhase(){found=new Set();hints=2;$('hintStatus').textContent='Dicas disponíveis: 2';$('message').textContent='Toque na primeira letra e arraste até a última.';$('factCards').innerHTML='<p class="empty">As explicações aparecerão aqui quando você encontrar as palavras.</p>';buildPuzzle();render();updateHud()}
function completePhase(){const p=PHASES[phase],card=$('reward'+(phase+1));card.classList.add('unlocked');card.innerHTML=`${p.medal}<strong>${p.reward}</strong>`;if(phase<2){$('modalIcon').textContent=p.medal;$('modalTitle').textContent=p.reward;$('modalText').textContent=`Você encontrou todas as palavras e acumulou ${coins} moedas.`;$('nextBtn').textContent='Próxima fase';$('phaseModal').classList.remove('hidden')}else{$('finalResult').textContent=`${score} pontos e ${coins} moedas`;$('victoryModal').classList.remove('hidden')}play('vitoria');coinRain()}
function start(){$('cover').classList.add('hidden');$('app').classList.remove('hidden');initPhase()}
$('startBtn').onclick=start;$('hintBtn').onclick=hint;$('helpBtn').onclick=()=>$('helpModal').classList.remove('hidden');$('closeHelp').onclick=()=>$('helpModal').classList.add('hidden');$('nextBtn').onclick=()=>{$('phaseModal').classList.add('hidden');phase++;initPhase();scrollTo({top:0,behavior:'smooth'})};$('againBtn').onclick=()=>{$('victoryModal').classList.add('hidden');phase=0;coins=0;score=0;document.querySelectorAll('.reward-row article').forEach((x,i)=>{x.classList.remove('unlocked');x.innerHTML=`🔒<strong>${['Explorador','Conector','Neuro Mestre'][i]}</strong>`});initPhase()};$('fontUp').onclick=()=>{font=Math.min(26,font+2);document.documentElement.style.setProperty('--font',font+'px')};$('fontDown').onclick=()=>{font=Math.max(16,font-2);document.documentElement.style.setProperty('--font',font+'px')};$('contrastBtn').onclick=()=>{document.body.classList.toggle('contrast');$('contrastBtn').setAttribute('aria-pressed',document.body.classList.contains('contrast'))};$('soundBtn').onclick=()=>{soundOn=!soundOn;$('soundBtn').textContent=soundOn?'🔊 Som':'🔇 Som';$('soundBtn').setAttribute('aria-pressed',soundOn)};$('readBtn').onclick=()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`${$('phaseTitle').textContent}. ${$('phaseIntro').textContent}. ${$('message').textContent}`);u.lang='pt-BR';u.rate=.9;speechSynthesis.speak(u)};$('grid').addEventListener('pointermove',e=>{if(!selecting)return;const cell=document.elementFromPoint(e.clientX,e.clientY)?.closest('.letter');if(cell)extend(Number(cell.dataset.index))});document.addEventListener('pointerup',()=>{if(selecting)finish()});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
})();
